version: 1.0.{build}

environment:
  global:
    APPVEYOR_OS_NAME: windows
  matrix:
  #MSYS2 Building
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x86
      BUILDER: MSYS2

  #VisualStudio Building
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x86
      BUILDER : VS
      BITS: 32
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x64
      BUILDER : VS
      BITS: 64

configuration: Debug
shallow_clone: true
clone_depth: 10

init:
- set MSYS2_PATH=c:\msys64
- set CHERE_INVOKING=1
- if "%BUILDER%_%PLATFORM%"=="MSYS2_x86" set MSYSTEM=MINGW32
- if "%BUILDER%_%PLATFORM%"=="MSYS2_x64" set MSYSTEM=MINGW64
- '%MSYS2_PATH%\usr\bin\bash -lc "pacman --noconfirm -S --needed unzip rsync"'
- if "%BUILDER%"=="VS" set PATH=%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin;%PATH%

install:
- cd ..
- git clone --depth=1 --branch=master https://github.com/openframeworks/openFrameworks
- git clone --depth=1 --branch=master https://github.com/danomatika/ofxMidi openframeworks/addons/ofxMidi
- git clone --depth=1 --branch=master https://github.com/npisanti/ofxAudioFile openframeworks/addons/ofxAudioFile
- call openFrameworks\scripts\ci\addons\install.cmd


build_script:
- cd %OF_PATH%
- rm -rf addons/ofxPDSP/example_android
- rm -rf addons/ofxPDSP/example_ios
- scripts\ci\addons\build.cmd


